# Generated by Django 5.1.7 on 2025-03-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(default=False)),
                ('dateUpdated', models.DateTimeField(auto_now=True))
            ],
        ),
    ]
