# Generated by Django 5.1.7 on 2025-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateCreated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
