# Generated by Django 5.1.7 on 2025-03-29 13:03

from django.db import migrations, models
from django.utils.timezone import now

def set_default_date(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.filter(dateCreated__isnull=True):
        task.dateCreated = now()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_datecreated_task_dateupdated'),
    ]

    operations = [
        migrations.RunPython(set_default_date),
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateTimeField(default=False),
        ),
    ]

